# Generated by `nixos-generate-config` at install time, then committed here so
# the flake is self-contained. Re-run `nixos-generate-config --no-filesystems`
# (and merge any new kernel modules) if you swap hardware.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # ----- Bootloader -----
  # The original /etc/nixos/configuration.nix had these; moving them here
  # alongside the rest of the boot/kernel config keeps the host config tidy.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # ----- Optional Ryzen / NVMe tunables -----
  # `amd_pstate=active`: enables the modern AMD P-state cpufreq driver. Better
  # perf-per-watt on Ryzen 5000-series than the legacy acpi-cpufreq fallback.
  # The other three are precautionary fixes for NVMe timeout/freeze issues —
  # safe to keep, can be removed if you don't see those symptoms.
  boot.kernelParams = [
    "amd_pstate=active"
    # "nvme_core.default_ps_max_latency_us=0" # only if NVMe sleeps too aggressively
    # "nvme_core.io_timeout=4294967295"        # only if NVMe times out
    # "pcie_aspm=off"                          # only if PCIe ASPM causes drops
  ];

  # ----- From `nixos-generate-config` on the live G14 -----
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0cbffacb-dc0c-4c8c-871c-d5f627a9e7d1";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/44CA-742C";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/04796f3c-72bd-4ea7-bdf0-792f0490adf6"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
